### ISSUE TITLE
Rubra RedDog error

### ISSUE THREAD

**Issue by vealvarez** [bjpop/rubra#28]
Hello, I am running RedDog and I am getting the error that is detailed below. I reported this problem in RedDog GitHub and they suggested that it could be a problem with Rubra and server permissions. I am running the pipeline on a torque/qsub system.  Could you help me? Thanks in advance!

Starting pipeline...
155 jobs to be executed in total
Traceback (most recent call last):
  File "/usr/local/bin/rubra", line 11, in <module>
    load_entry_point('Rubra==0.1.5', 'console_scripts', 'rubra')()
  File "build/bdist.linux-x86_64/egg/rubra/rubra.py", line 66, in main
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2680, in pipeline_run
ruffus.ruffus_exceptions.RethrownJobError:

    Exceptions running jobs for

    'def RedDog.makeDir(...):'

    Original exception:

    Exception #1
    exceptions.Exception(qsub command failed with exit status: 172):
    for RedDog.makeDir.Job = [False -> dir.makeDir.Success]

    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 517, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 447, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "RedDog.py", line 955, in makeDir
        runStageCheck('makeDir', flagFile, outPrefix, full_sequence_list_string)
      File "build/bdist.linux-x86_64/egg/rubra/utils.py", line 128, in runStageCheck
        status = runStage(stage, *args)
      File "build/bdist.linux-x86_64/egg/rubra/utils.py", line 144, in runStage
        exitStatus = distributedCommand(stage, commandStr, pipeline_options)
      File "build/bdist.linux-x86_64/egg/rubra/utils.py", line 122, in distributedCommand
        return script.runJobAndWait(stage, logDir, verbosity)
      File "build/bdist.linux-x86_64/egg/rubra/cluster_job.py", line 65, in runJobAndWait
        jobID = self.launch()
      File "build/bdist.linux-x86_64/egg/rubra/cluster_job.py", line 138, in launch
        str(returnCode)))
    Exception: qsub command failed with exit status: 172

**Comment by vealvarez** [comment]
Hello again, I have ran RedDog using root user and now the error is the following

Starting pipeline...
155 jobs to be executed in total
Traceback (most recent call last):
  File "/usr/local/bin/rubra", line 11, in <module>
    load_entry_point('Rubra==0.1.5', 'console_scripts', 'rubra')()
  File "build/bdist.linux-x86_64/egg/rubra/rubra.py", line 66, in main
  File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 2680, in pipeline_run
ruffus.ruffus_exceptions.RethrownJobError: 
    
    Exceptions running jobs for
    
    'def RedDog.makeDir(...):'
    
    Original exception:
    
    Exception #1
    exceptions.Exception(qsub command failed with exit status: 1):
    for RedDog.makeDir.Job = [False -> dir.makeDir.Success]
    
    Traceback (most recent call last):
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 517, in run_pooled_job_without_exceptions
        return_value =  job_wrapper(param, user_defined_work_func, register_cleanup, touch_files_only)
      File "build/bdist.linux-x86_64/egg/ruffus/task.py", line 447, in job_wrapper_io_files
        ret_val = user_defined_work_func(*param)
      File "RedDog.py", line 955, in makeDir
        runStageCheck('makeDir', flagFile, outPrefix, full_sequence_list_string)
      File "build/bdist.linux-x86_64/egg/rubra/utils.py", line 128, in runStageCheck
        status = runStage(stage, *args)
      File "build/bdist.linux-x86_64/egg/rubra/utils.py", line 144, in runStage
        exitStatus = distributedCommand(stage, commandStr, pipeline_options)
      File "build/bdist.linux-x86_64/egg/rubra/utils.py", line 122, in distributedCommand
        return script.runJobAndWait(stage, logDir, verbosity)
      File "build/bdist.linux-x86_64/egg/rubra/cluster_job.py", line 65, in runJobAndWait
        jobID = self.launch()
      File "build/bdist.linux-x86_64/egg/rubra/cluster_job.py", line 138, in launch
        str(returnCode)))
    Exception: qsub command failed with exit status: 1
